"use client";

import { useEffect, useRef, useState } from "react";
import { AiDumpHero } from "./AiDumpHero";
import { Avatar } from "../Avatar";
import { AvatarUpload } from "./AvatarUpload";
import { ContextSources, type Snippet } from "./ContextSources";
import { SelfDiscovery } from "./SelfDiscovery";
import { saveTwin } from "./actions";
import { GoalFollowUpQuestions } from "./GoalFollowUpQuestions";
import { LoadingScreen } from "../LoadingScreen";
import { phoneLooksComplete } from "@/lib/phone";
import { Capacitor } from "@capacitor/core";

// Parse existing ai_export_blob back into structured snippets so the wizard
// can rehydrate URL-sourced context across page reloads. Snippets were
// originally appended as `# {label} ({source})\n{text}` blocks.
function parseSnippets(blob: string): {
  snippets: Snippet[];
  aiDump: string;
} {
  if (!blob.trim()) return { snippets: [], aiDump: "" };
  const sections = blob.split(/\n\n+(?=#\s+)/g);
  const snippets: Snippet[] = [];
  let aiDump = "";
  for (const raw of sections) {
    const m = raw.match(/^#\s+(.+?)\s+\((.+?)\)\s*\n([\s\S]+)$/);
    if (m) {
      snippets.push({
        id: Math.random().toString(36).slice(2, 10),
        label: m[1].trim(),
        source: m[2].trim(),
        text: m[3].trim()
      });
    } else {
      // Anything that doesn't match the header pattern is the AI dump.
      aiDump = aiDump
        ? `${aiDump}\n\n${raw.trim()}`
        : raw.trim();
    }
  }
  return { snippets, aiDump };
}

// Serialize back to the blob shape on save.
function serializeBlob(snippets: Snippet[], aiDump: string): string {
  const parts: string[] = [];
  for (const s of snippets) {
    if (s.text.trim())
      parts.push(`# ${s.label} (${s.source})\n${s.text.trim()}`);
  }
  if (aiDump.trim()) parts.push(aiDump.trim());
  return parts.join("\n\n");
}

type Initial = {
  display_name: string;
  phone_number: string;
  goals: string;
  deal_preferences: string;
  communication_style: string;
  deal_breakers: string;
  ai_export_blob: string;
  avatar_url: string;
  hometown: string;
  current_city: string;
  achievements: string;
};

const STEPS = [
  { key: "you", label: "You" },
  { key: "sources", label: "Sources" },
  { key: "ai_dump", label: "AI memory" },
  { key: "refine", label: "Refine" }
] as const;

export function OnboardingWizard({
  initial,
  userId
}: {
  initial: Initial;
  userId: string;
}) {
  const [step, setStep] = useState(0);
  const [state, setState] = useState<Initial>(initial);
  // Goal-aware follow-up answers — generated by Claude in
  // GoalFollowUpQuestions. Stored separately from `goals` so they don't
  // overwrite the user's typed goal on each keystroke; merged at save.
  const [followUpBlock, setFollowUpBlock] = useState<string>("");
  // Composed goals string — user's typed goals + Claude-generated
  // follow-up Q&A block. Declared early so all useEffects + JSX below
  // can use it. Falls back to plain state.goals when no follow-ups.
  const composedGoals = followUpBlock
    ? `${state.goals.trim()}\n\n--- Goal context Q&A ---\n${followUpBlock}`
    : state.goals;

  // Jack's call: EVERY step pill is always clickable, even for first-time
  // users. The original "only step ≤ current" gate annoyed users who
  // wanted to peek ahead or jump back to fix a typo. Required-field
  // enforcement still happens at save (display_name + goals must exist),
  // but navigation between steps is free. `hasCompletedOnboarding` is
  // kept so other UX bits (smart prefill heuristics) can still tell new
  // users from returners.
  const hasCompletedOnboarding =
    (initial.goals || "").trim().length > 5 ||
    (initial.deal_preferences || "").trim().length > 0 ||
    (initial.communication_style || "").trim().length > 0 ||
    (initial.deal_breakers || "").trim().length > 0 ||
    (initial.ai_export_blob || "").trim().length > 80;
  const set = <K extends keyof Initial>(k: K, v: Initial[K]) =>
    setState((s) => ({ ...s, [k]: v }));
  const [native, setNative] = useState(false);
  useEffect(() => setNative(Capacitor.isNativePlatform()), []);
  const phoneReady = phoneLooksComplete(state.phone_number) || (native && !state.phone_number.trim());

  // Cinematic pacing: every step change starts at the top of the page
  // with a fresh entrance (also fixes landing mid-page via scroll
  // restoration). Smooth unless the user prefers reduced motion.
  useEffect(() => {
    if (typeof window === "undefined") return;
    const reduce = window.matchMedia?.(
      "(prefers-reduced-motion: reduce)"
    ).matches;
    window.scrollTo({ top: 0, behavior: reduce ? "auto" : "smooth" });
  }, [step]);

  // Hydrate URL snippets + AI dump from the existing blob on first mount.
  const initialParsed = useRef(parseSnippets(initial.ai_export_blob || ""));
  const [snippets, setSnippets] = useState<Snippet[]>(
    initialParsed.current.snippets
  );
  const [aiDump, setAiDump] = useState<string>(
    initialParsed.current.aiDump
  );

  // Prefill from the /generate-free-portfolio funnel (and quick-join):
  // if the visitor pasted their personal intelligence before signing up,
  // we stashed it in localStorage. On first mount, seed the AI dump +
  // name so their portfolio/twin builds from it instead of a blank form.
  const seededRef = useRef(false);
  useEffect(() => {
    if (seededRef.current) return;
    seededRef.current = true;
    try {
      // Info the user committed to an invite proposal (lock-in inputs on
      // the /[slug] page) rides into the twin context here, so the twin
      // can actually deliver what was promised.
      try {
        const rawInfo = localStorage.getItem("syncedin-claim-info");
        if (rawInfo) {
          const ci = JSON.parse(rawInfo) as {
            proposal?: string;
            info?: Record<string, string>;
          };
          const entries = Object.entries(ci?.info ?? {}).filter(
            ([, v]) => typeof v === "string" && v.trim().length > 0
          );
          if (entries.length > 0) {
            const block = `--- Info I committed to the proposal ---\n${
              ci?.proposal ? `Proposal: ${ci.proposal}\n` : ""
            }${entries.map(([k, v]) => `${k}: ${v.trim()}`).join("\n")}`;
            setAiDump((d) =>
              d.includes("Info I committed to the proposal")
                ? d
                : `${d ? `${d}\n\n` : ""}${block}`
            );
          }
          localStorage.removeItem("syncedin-claim-info");
        }
      } catch {
        /* malformed claim info: ignore */
      }
      const raw = localStorage.getItem("syncedin-portfolio-seed");
      if (!raw) return;
      const seed = JSON.parse(raw) as { name?: string; dump?: string };
      if (seed?.dump && (initial.ai_export_blob || "").trim().length < 20) {
        setAiDump((d) => (d.trim().length < 20 ? seed.dump! : d));
      }
      if (seed?.name && !(initial.display_name || "").trim()) {
        setState((s) => (s.display_name.trim() ? s : { ...s, display_name: seed.name! }));
      }
      localStorage.removeItem("syncedin-portfolio-seed");
    } catch {
      /* ignore */
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Keep ai_export_blob in state synchronized with snippets + aiDump
  // so the hidden form input always submits the latest combined blob.
  useEffect(() => {
    setState((s) => ({
      ...s,
      ai_export_blob: serializeBlob(snippets, aiDump)
    }));
  }, [snippets, aiDump]);

  // Smart prefill for the Refine step. The first time the user lands on
  // step 4 AND any of the three refine fields is empty, hit
  // /api/suggest-refine which uses Claude to draft answers from the
  // user's goals + ai_export_blob. The textareas then arrive populated
  // so the user is editing — not writing from blank. Far higher
  // completion rate.
  const refineSuggestTried = useRef(false);
  const [refineLoading, setRefineLoading] = useState(false);
  // Drives the cool full-screen LoadingScreen — shown ONLY during the
  // save-twin → chat handoff (Jack: "I only want to use that cool loading
  // screen after someone saves their twin"). Every other route uses a
  // light skeleton so navigation stays snappy.
  const [saving, setSaving] = useState(false);
  useEffect(() => {
    if (STEPS[step].key !== "refine") return;
    if (refineSuggestTried.current) return;
    const anyEmpty =
      !state.deal_preferences.trim() ||
      !state.communication_style.trim() ||
      !state.deal_breakers.trim();
    if (!anyEmpty) {
      refineSuggestTried.current = true;
      return;
    }
    // Don't bother if the user has zero signal yet.
    if (
      state.goals.trim().length < 8 &&
      state.ai_export_blob.trim().length < 80
    ) {
      refineSuggestTried.current = true;
      return;
    }
    refineSuggestTried.current = true;
    setRefineLoading(true);
    (async () => {
      try {
        const r = await fetch("/api/suggest-refine", {
          method: "POST",
          headers: { "content-type": "application/json" },
          body: JSON.stringify({
            display_name: state.display_name,
            goals: composedGoals,
            ai_export_blob: state.ai_export_blob,
            current_city: state.current_city,
            hometown: state.hometown,
            existing: {
              deal_preferences: state.deal_preferences,
              communication_style: state.communication_style,
              deal_breakers: state.deal_breakers
            }
          })
        });
        const j = await r.json();
        setState((s) => ({
          ...s,
          deal_preferences:
            s.deal_preferences.trim() || j.deal_preferences || "",
          communication_style:
            s.communication_style.trim() || j.communication_style || "",
          deal_breakers: s.deal_breakers.trim() || j.deal_breakers || ""
        }));
      } catch {
        /* leave empty — user can write from scratch */
      } finally {
        setRefineLoading(false);
      }
    })();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [step]);

  // Persistent draft save.
  //
  // Two layers so paste-and-navigate never drops the AI memory blob:
  //  1. Debounced fetch on every state change (700ms). Catches the common
  //     "user types, pauses, keeps typing" case.
  //  2. navigator.sendBeacon on pagehide + visibilitychange + beforeunload.
  //     sendBeacon is fire-and-forget and the browser GUARANTEES delivery
  //     even when the page is unloading — which is exactly when fetch()
  //     gets cancelled.
  //
  // The ref always holds the latest serialized payload so the beacon
  // handlers can read it synchronously without stale-closure issues.
  const saveTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const latestPayload = useRef<string>("");
  useEffect(() => {
    const payload = JSON.stringify({
      display_name: state.display_name,
      phone_number: state.phone_number,
      avatar_url: state.avatar_url,
      goals: composedGoals,
      deal_preferences: state.deal_preferences,
      communication_style: state.communication_style,
      deal_breakers: state.deal_breakers,
      ai_export_blob: state.ai_export_blob,
      hometown: state.hometown,
      current_city: state.current_city,
      achievements: state.achievements
    });
    latestPayload.current = payload;

    if (saveTimer.current) clearTimeout(saveTimer.current);
    saveTimer.current = setTimeout(() => {
      fetch("/api/save-twin-draft", {
        method: "POST",
        headers: { "content-type": "application/json" },
        keepalive: true,
        body: payload
      }).catch(() => {
        /* fire-and-forget; the beacon below also covers us */
      });
    }, 700);
    return () => {
      if (saveTimer.current) clearTimeout(saveTimer.current);
    };
  }, [state]);

  // Beacon-on-unload — guarantees the latest draft hits the server even when
  // fetch() would be cancelled mid-flight by navigation.
  useEffect(() => {
    function flush() {
      const payload = latestPayload.current;
      if (!payload) return;
      try {
        if (typeof navigator !== "undefined" && navigator.sendBeacon) {
          const blob = new Blob([payload], { type: "application/json" });
          navigator.sendBeacon("/api/save-twin-draft", blob);
        } else {
          fetch("/api/save-twin-draft", {
            method: "POST",
            headers: { "content-type": "application/json" },
            body: payload,
            keepalive: true
          }).catch(() => {});
        }
      } catch {
        /* never throw during unload */
      }
    }
    const onVis = () => {
      if (document.visibilityState === "hidden") flush();
    };
    window.addEventListener("pagehide", flush);
    window.addEventListener("beforeunload", flush);
    document.addEventListener("visibilitychange", onVis);
    return () => {
      window.removeEventListener("pagehide", flush);
      window.removeEventListener("beforeunload", flush);
      document.removeEventListener("visibilitychange", onVis);
    };
  }, []);

  // Append a snippet (used by SelfDiscovery after "this is me" confirm)
  function appendBlob(text: string, label: string, source: string) {
    setSnippets((prev) => [
      ...prev,
      {
        id: Math.random().toString(36).slice(2, 10),
        label,
        source,
        text
      }
    ]);
  }

  const canAdvance = (() => {
    switch (STEPS[step].key) {
      case "you":
        return state.display_name.trim().length > 0 && phoneReady;
      case "sources":
        return state.goals.trim().length > 0;
      default:
        return true;
    }
  })();

  // Per-step "has the user added any real signal yet?" — drives the
  // skip / continue label swap on the top nav button. Required-field
  // gates still live in canAdvance; this is purely cosmetic.
  const stepHasContent = (() => {
    switch (STEPS[step].key) {
      case "you":
        return (
          state.display_name.trim().length > 0 ||
          state.phone_number.trim().length > 0 ||
          !!state.avatar_url ||
          state.current_city.trim().length > 0 ||
          state.hometown.trim().length > 0
        );
      case "sources":
        return (
          state.goals.trim().length > 0 ||
          snippets.length > 0
        );
      case "ai_dump":
        return aiDump.trim().length > 0;
      case "refine":
        return (
          state.deal_preferences.trim().length > 0 ||
          state.communication_style.trim().length > 0 ||
          state.deal_breakers.trim().length > 0
        );
      default:
        return false;
    }
  })();

  // Reusable nav row — small + sticky-friendly version goes at the top,
  // full version at the bottom. Kept in a function so they stay in lockstep.
  const NavRow = ({ compact = false }: { compact?: boolean }) => (
    <div
      className={`flex items-center justify-between ${
        compact ? "mb-3" : "mt-5"
      }`}
    >
      <button
        type="button"
        onClick={() => setStep((s) => Math.max(0, s - 1))}
        disabled={step === 0}
        className={compact ? "retro-btn text-xs" : "retro-btn"}
        style={{ visibility: step === 0 ? "hidden" : "visible" }}
      >
        ← back
      </button>
      <div
        className={compact ? "retro-dim text-[10px]" : "retro-dim text-xs"}
        style={{ color: "var(--text-dim)" }}
      >
        {step + 1} / {STEPS.length}
      </div>
      {step < STEPS.length - 1 ? (
        <button
          type="button"
          onClick={() => setStep((s) => Math.min(STEPS.length - 1, s + 1))}
          disabled={!canAdvance}
          className={
            compact
              ? "retro-btn retro-btn-primary text-xs"
              : "retro-btn retro-btn-primary"
          }
        >
          continue →
        </button>
      ) : (
        <button
          type="submit"
          disabled={
            !state.display_name.trim() ||
            !phoneReady ||
            !state.goals.trim() ||
            !state.deal_preferences.trim()
          }
          className={
            compact
              ? "retro-btn retro-btn-primary text-xs"
              : "retro-btn retro-btn-primary"
          }
        >
          {compact ? "save twin →" : "Save twin & go to dashboard"}
        </button>
      )}
    </div>
  );

  return (
    <form
      action={saveTwin}
      id="onboarding-form"
      // Real form submit == the "Save Twin And Start Connecting" button.
      // Flip on the cool full-screen loader for the save → chat handoff;
      // it stays up through the server action + redirect to /twin.
      onSubmit={() => setSaving(true)}
      // Hard guard: Enter inside a single-line input must NOT submit the form
      // and bounce the user to /dashboard mid-refine. Textareas keep Enter
      // (it's a newline), explicit submit click still works.
      onKeyDown={(e) => {
        const t = e.target as HTMLElement;
        if (
          e.key === "Enter" &&
          t.tagName !== "TEXTAREA" &&
          !(t.tagName === "BUTTON" && (t as HTMLButtonElement).type === "submit")
        ) {
          e.preventDefault();
        }
      }}
    >
      {saving && (
        <div
          style={{
            position: "fixed",
            inset: 0,
            zIndex: 100,
            background: "var(--bg)",
            display: "flex",
            alignItems: "center",
            justifyContent: "center"
          }}
        >
          <LoadingScreen
            lines={[
              `Building ${
                (state.display_name || "your").split(/\s+/)[0]
              }'s twin…`,
              "Wiring in everything you just gave it…",
              "Scanning the network for your best match…",
              "Opening your home base…"
            ]}
          />
        </div>
      )}
      <input type="hidden" name="display_name" value={state.display_name} />
      <input type="hidden" name="phone_number" value={state.phone_number} />
      <input type="hidden" name="native_app" value={native ? "yes" : "no"} />
      <input type="hidden" name="goals" value={composedGoals} />
      <input
        type="hidden"
        name="deal_preferences"
        value={state.deal_preferences}
      />
      <input
        type="hidden"
        name="communication_style"
        value={state.communication_style}
      />
      <input type="hidden" name="deal_breakers" value={state.deal_breakers} />
      <input
        type="hidden"
        name="ai_export_blob"
        value={state.ai_export_blob}
      />
      <input type="hidden" name="avatar_url" value={state.avatar_url} />
      <input type="hidden" name="hometown" value={state.hometown} />
      <input type="hidden" name="current_city" value={state.current_city} />
      <input type="hidden" name="achievements" value={state.achievements} />

      {/* Onboarding cinema layer: entrances, pill physics, connector
          fills. Pure presentation; reduced-motion turns it all off. */}
      <style>{`
        @keyframes ob-step-in {
          0% { opacity: 0; transform: translateY(14px) scale(0.992); }
          100% { opacity: 1; transform: none; }
        }
        .ob-step-in {
          animation: ob-step-in 0.45s cubic-bezier(0.2, 0.9, 0.3, 1) both;
        }
        .ob-pill {
          transition: transform 0.15s ease, background 0.25s ease,
            border-color 0.25s ease, color 0.25s ease;
        }
        @keyframes ob-pill-ring {
          0% { box-shadow: 0 0 0 0 var(--accent-glow); }
          70% { box-shadow: 0 0 0 9px rgba(0, 0, 0, 0); }
          100% { box-shadow: 0 0 0 0 rgba(0, 0, 0, 0); }
        }
        .ob-pill-current { animation: ob-pill-ring 2.2s ease-out infinite; }
        @keyframes ob-pill-pop {
          0% { transform: scale(0.55); }
          70% { transform: scale(1.12); }
          100% { transform: scale(1); }
        }
        .ob-pill-done { animation: ob-pill-pop 0.35s cubic-bezier(0.2, 1.2, 0.4, 1) both; }
        .ob-connector { transition: background 0.4s ease; }
        .ob-connector-done { background: var(--amber) !important; }
        @media (prefers-reduced-motion: reduce) {
          .ob-step-in, .ob-pill-current, .ob-pill-done { animation: none; }
        }
      `}</style>

      {/* Progress strip — step pills LEFT, continue/back nav RIGHT, all in
          a single row so the user never has to look around for "what next".
          We deliberately drop flex-wrap on the outer row + collapse the
          back button to a single arrow on the inline strip, so the row
          stays one line and Continue sits flush-right of the last pill. */}
      <div className="flex items-center justify-between gap-3 mb-6">
        <div
          className="flex items-center gap-2 flex-wrap"
          style={{ minWidth: 0, flex: "1 1 auto" }}
        >
        {STEPS.map((s, i) => {
          const done = i < step;
          const current = i === step;
          return (
            <div key={s.key} className="flex items-center gap-2">
              <button
                type="button"
                onClick={() => setStep(i)}
                className="flex items-center gap-2"
                style={{
                  background: "transparent",
                  border: 0,
                  padding: 0,
                  cursor: "pointer",
                  opacity: 1
                }}
              >
                <span
                  className={
                    done
                      ? "ob-pill ob-pill-done"
                      : current
                        ? "ob-pill ob-pill-current"
                        : "ob-pill"
                  }
                  style={{
                    width: 28,
                    height: 28,
                    borderRadius: "50%",
                    border: `2px solid ${
                      current || done
                        ? "var(--amber)"
                        : "var(--border-bright)"
                    }`,
                    background: done
                      ? "var(--amber)"
                      : current
                      ? "var(--panel-solid)"
                      : "transparent",
                    color: done ? "#fff" : "var(--text)",
                    display: "inline-flex",
                    alignItems: "center",
                    justifyContent: "center",
                    fontSize: 12,
                    fontWeight: 700
                  }}
                >
                  {done ? "✓" : i + 1}
                </span>
                <span
                  className="text-sm"
                  style={{
                    color: current
                      ? "var(--text)"
                      : "var(--text-dim)",
                    fontWeight: current ? 700 : 500
                  }}
                >
                  {s.label}
                </span>
              </button>
              {i < STEPS.length - 1 && (
                <span
                  className={
                    done ? "ob-connector ob-connector-done" : "ob-connector"
                  }
                  style={{
                    width: 14,
                    height: 1,
                    background: "var(--border-bright)"
                  }}
                />
              )}
            </div>
          );
        })}
        </div>
        <div
          className="flex items-center gap-2 shrink-0"
          style={{ marginLeft: 8 }}
        >
          <button
            type="button"
            onClick={() => setStep((s) => Math.max(0, s - 1))}
            disabled={step === 0}
            className="retro-btn text-xs"
            style={{
              visibility: step === 0 ? "hidden" : "visible",
              padding: "6px 10px"
            }}
            aria-label="Back"
          >
            ←
          </button>
          {/* Forward button. Three states, all rendered with unique
              key props so React always builds a fresh DOM node — this
              is what historically blocked the "continue auto-submits"
              bug from re-appearing. Never reuse the same key across
              type=button and type=submit.

                1. step has user content + not last → "continue →" (button)
                2. step empty + not last → "skip →" (button, dim)
                3. last step → "Save Twin And Start Connecting" (submit) */}
          {step < STEPS.length - 1 ? (
            stepHasContent ? (
              <button
                key="continue-top-filled"
                type="button"
                onClick={() =>
                  setStep((s) => Math.min(STEPS.length - 1, s + 1))
                }
                disabled={!canAdvance}
                className="retro-btn retro-btn-primary text-xs"
                style={{ padding: "6px 14px" }}
              >
                continue →
              </button>
            ) : (
              <button
                key="skip-top-empty"
                type="button"
                onClick={() =>
                  setStep((s) => Math.min(STEPS.length - 1, s + 1))
                }
                disabled={!canAdvance}
                className="retro-btn text-xs"
                style={{ padding: "6px 14px" }}
                title="Skip this step — you can come back any time"
              >
                skip →
              </button>
            )
          ) : (
            <button
              key="save-twin-top"
              type="submit"
              disabled={
                !state.display_name.trim() ||
                !phoneReady ||
                !state.goals.trim() ||
                !state.deal_preferences.trim()
              }
              className="retro-btn retro-btn-primary text-xs"
              style={{ padding: "6px 14px" }}
            >
              Save Twin And Start Connecting →
            </button>
          )}
        </div>
      </div>

      <div key={STEPS[step].key} className="retro-panel retro-shadow p-6 ob-step-in">
        {/* STEP 1 — You: name + photo together */}
        {STEPS[step].key === "you" && (
          <div>
            <div className="retro-label">step 1 of 4</div>
            <h2 className="retro-h1 text-2xl mt-2">Let&apos;s start with you.</h2>
            <p className="text-sm mt-2" style={{ color: "var(--text-dim)" }}>
              Phone gets your twin out of the email trap. Add it here for
              iMessage, RCS, or SMS alerts when something important happens.
            </p>

            <label className="block mt-5">
              <div
                className="text-sm font-semibold"
                style={{ color: "var(--text)" }}
              >
                Your name
              </div>
              <input
                autoFocus
                value={state.display_name}
                onChange={(e) => set("display_name", e.target.value)}
                placeholder="Jane Doe"
                className="retro-input mt-1"
              />
            </label>
            <label className="block mt-3">
              <div
                className="text-sm font-semibold"
                style={{ color: "var(--text)" }}
              >
                Phone for iMessage or SMS
              </div>
              <input
                value={state.phone_number}
                onChange={(e) => set("phone_number", e.target.value)}
                type="tel"
                inputMode="tel"
                autoComplete="tel"
                placeholder="+1 415 555 0123"
                className="retro-input mt-1"
              />
              <p
                className="text-xs mt-1"
                style={{ color: "var(--text-dim)" }}
              >
                {native ? "Optional for phone updates. You can choose notification preferences in Settings." : "Private phone for connection updates. Notification preferences are in Settings."}
              </p>
              {state.phone_number.trim() && !phoneReady && (
                <p className="text-xs mt-1 retro-red">
                  Enter a valid phone number with area code.
                </p>
              )}
            </label>

            {/* Photo + locations row — Jack's call: kill the "Choose Photo"
                button and the standalone "where you live / where you're
                from" block. The avatar (clickable / drag-drop) sits on the
                left, the two city inputs stack vertically next to it. */}
            <div
              className="mt-5"
              style={{
                display: "flex",
                alignItems: "flex-start",
                gap: 18,
                flexWrap: "wrap"
              }}
            >
              <div>
                <div
                  className="text-xs font-semibold mb-2"
                  style={{ color: "var(--text-dim)" }}
                >
                  Your photo
                </div>
                <AvatarUpload
                  id={userId}
                  name={state.display_name}
                  value={state.avatar_url}
                  onChange={(next) => set("avatar_url", next)}
                />
              </div>
              <div style={{ flex: "1 1 240px", minWidth: 240 }}>
                <label className="block">
                  <div
                    className="text-sm font-semibold"
                    style={{ color: "var(--text)" }}
                  >
                    Where do you live now?
                  </div>
                  <input
                    value={state.current_city}
                    onChange={(e) => set("current_city", e.target.value)}
                    placeholder="San Francisco, CA"
                    className="retro-input mt-1"
                  />
                </label>
                <label className="block mt-3">
                  <div
                    className="text-sm font-semibold"
                    style={{ color: "var(--text)" }}
                  >
                    Where are you from?
                  </div>
                  <input
                    value={state.hometown}
                    onChange={(e) => set("hometown", e.target.value)}
                    placeholder="Detroit, MI"
                    className="retro-input mt-1"
                  />
                </label>
              </div>
            </div>

            {/* Intelligent auto-discovery — finds you on the web and pulls
                a clean dossier into your context if you confirm. Auto-jumps
                to the next step after a successful "this is me" pick. */}
            <SelfDiscovery
              name={state.display_name}
              onConfirm={(snippet, source) =>
                appendBlob(snippet, "Public footprint", source)
              }
              onAdvance={() =>
                setStep((s) => Math.min(STEPS.length - 1, s + 1))
              }
            />

            <StepFooterNext
              canAdvance={canAdvance}
              hasContent={stepHasContent}
              onNext={() =>
                setStep((s) => Math.min(STEPS.length - 1, s + 1))
              }
            />
          </div>
        )}

        {/* STEP 2 — Sources: goals + URL-based context */}
        {STEPS[step].key === "sources" && (
          <div>
            <div className="retro-label">step 2 of 4</div>
            <h2 className="retro-h1 text-2xl mt-2">
              Where can your twin learn about you?
            </h2>
            {/* Jack's call: drop the 'add LinkedIn / X / Instagram' helper
                line. ContextSources already shows those affordances inside
                its own UI, so the line was duplicating what's already
                visible below. */}

            <div className="mt-6 space-y-6">
              <label className="block">
                <div
                  className="text-sm font-semibold"
                  style={{ color: "var(--text)" }}
                >
                  What&apos;s your main goal in life right now?
                </div>
                <p
                  className="text-xs mt-1"
                  style={{ color: "var(--text-dim)" }}
                >
                  I&apos;ll find the perfect person to make it happen.
                  Feel free to list multiple.
                </p>
                <textarea
                  value={state.goals}
                  onChange={(e) => set("goals", e.target.value)}
                  rows={4}
                  placeholder="e.g. Raising my Series A. Hiring a Head of Design. Finding builders to take over my open-source projects."
                  className="retro-input mt-2"
                  style={{ minHeight: 110 }}
                />
              </label>

              {/* Goal-aware follow-ups. When the user types a real goal,
                  Claude generates 3-5 tailored questions to sharpen the
                  twin context. Answers append to the goals string so no
                  schema changes needed. Intent comes from the landing
                  page tile (?intent=cofounder|investors|advisors|idea). */}
              <GoalFollowUpQuestions
                goal={state.goals}
                intent={
                  typeof window !== "undefined"
                    ? new URLSearchParams(window.location.search).get(
                        "intent"
                      ) ?? ""
                    : ""
                }
                onAnswersChange={(block) => {
                  // Stash the answers block in state so step-save merges
                  // it into goals before persisting. We store the raw
                  // block + the user's typed goals separately so further
                  // edits don't duplicate.
                  setFollowUpBlock(block);
                }}
              />

              <ContextSources
                snippets={snippets}
                onChange={setSnippets}
              />
            </div>

            <StepFooterNext
              canAdvance={canAdvance}
              hasContent={stepHasContent}
              onNext={() =>
                setStep((s) => Math.min(STEPS.length - 1, s + 1))
              }
            />
          </div>
        )}

        {/* STEP 3 — AI memory: paste from ChatGPT/Claude/Gemini/Grok */}
        {STEPS[step].key === "ai_dump" && (
          <div>
            <div className="retro-label">step 3 of 4</div>
            <h2 className="retro-h1 text-2xl mt-2">
              Let the AI you already use describe you.
            </h2>
            <p className="text-sm mt-2" style={{ color: "var(--text-dim)" }}>
              The AI you already talk to knows your goals, voice, and how
              you think. Copy the prompt, open your AI, paste the answer
              below. Skip if you already added enough from sources.
            </p>

            {/* If they've already pasted something in a prior session, don't
                blast them with the full "how to do this" hero on re-entry —
                show a tiny "redo it" chip and put the textarea front-and-
                center. New users (empty dump) still see the full hero. */}
            {aiDump.trim().length > 0 ? (
              <div className="mt-5">
                <details>
                  <summary
                    className="text-xs cursor-pointer inline-flex items-center gap-2 retro-panel"
                    style={{
                      padding: "8px 12px",
                      color: "var(--text-dim)",
                      listStyle: "none"
                    }}
                  >
                    <span style={{ color: "var(--green)" }}>✓</span>
                    <span>
                      AI memory saved ({aiDump.trim().length.toLocaleString()}{" "}
                      chars). Click to redo with a fresh prompt.
                    </span>
                  </summary>
                  <div className="mt-3">
                    <AiDumpHero />
                  </div>
                </details>
              </div>
            ) : (
              <div className="mt-5">
                <AiDumpHero />
              </div>
            )}

            <label className="block mt-5">
              <div
                className="text-sm font-semibold"
                style={{ color: "var(--text)" }}
              >
                {aiDump.trim().length > 0
                  ? "Your AI memory (edit anytime)"
                  : "Paste the AI's full answer"}
              </div>
              <textarea
                value={aiDump}
                onChange={(e) => setAiDump(e.target.value)}
                onBlur={() => {
                  // Force-flush the latest draft immediately when the
                  // textarea loses focus — guards against losing a fresh
                  // paste if the user navigates within the 700ms debounce.
                  try {
                    const payload = latestPayload.current;
                    if (!payload) return;
                    if (
                      typeof navigator !== "undefined" &&
                      navigator.sendBeacon
                    ) {
                      navigator.sendBeacon(
                        "/api/save-twin-draft",
                        new Blob([payload], { type: "application/json" })
                      );
                    }
                  } catch {
                    /* never throw */
                  }
                }}
                rows={10}
                placeholder="Paste here. Snippets you added on the Sources step are kept separately and remain editable there."
                className="retro-input mt-1 font-mono text-sm"
                style={{ minHeight: 240 }}
              />
            </label>

            <StepFooterNext
              canAdvance={canAdvance}
              hasContent={stepHasContent}
              onNext={() =>
                setStep((s) => Math.min(STEPS.length - 1, s + 1))
              }
            />
          </div>
        )}

        {/* STEP 4 — Refine: high-signal seeds for twin-to-twin conversations.
            Questions rewritten to surface CONCRETE asks + offers that
            twin conversations can actually trade on. The smart prefill
            (useEffect above) drafts answers from the user's existing
            goals + ai_export_blob so they edit instead of write blank. */}
        {STEPS[step].key === "refine" && (
          <div>
            <div className="retro-label">step 4 of 4</div>
            <h2 className="retro-h1 text-2xl mt-2">
              The three lines your twin actually negotiates on.
            </h2>
            <p className="text-sm mt-2" style={{ color: "var(--text-dim)" }}>
              These three answers seed every twin-to-twin conversation —
              the ask, the offer, and the line you won&apos;t cross. We
              drafted suggestions from what you already told us. Edit them
              so they sound like you.
            </p>
            {refineLoading && (
              <p
                className="text-xs mt-2"
                style={{ color: "var(--amber-bright)" }}
              >
                drafting answers from your goals + AI memory…
              </p>
            )}
            <div className="mt-5 space-y-5">
              <DeepField
                label="What can you OFFER the network right now?"
                helper="Concrete things you can introduce, fund, build, advise on, host, or open doors for. The more specific the offer, the more matches your twin can make. Treat this as the bait other people can grab."
                placeholder={`e.g. Warm intros to ~40 enterprise CTOs from my prior role. Two hours/week to advise pre-seed founders in dev tooling. A short loom critique of any landing page in B2B SaaS.`}
                rows={5}
                value={state.deal_preferences}
                onChange={(v) => set("deal_preferences", v)}
              />
              <DeepField
                label="How should your twin SHOW UP for you?"
                helper="The voice, the speed, the level of pushback. Should it ask the hard question or smooth things over? Use first names or full names? Mention specific deals you've done or stay vague? This is your twin's operating posture."
                placeholder={`e.g. Direct, low-hedge. Lead with the point. Push hard if someone is being vague — I'd rather lose a soft fit than waste a 30-minute call. Never use 'just' or em-dashes. Use first names always.`}
                rows={4}
                value={state.communication_style}
                onChange={(v) => set("communication_style", v)}
              />
              <DeepField
                label="What makes you instantly walk away?"
                helper="The hard no-gos your twin should detect and decline before they reach you. Categories of asks, behaviors, value mismatches. Listing them here means your inbox stays for the conversations that actually matter."
                placeholder={`e.g. Anyone trying to sell me their service in the first message. Pitch decks before a real conversation. People who can't name a specific thing they're working on. Anything that smells like an MLM.`}
                rows={4}
                value={state.deal_breakers}
                onChange={(v) => set("deal_breakers", v)}
              />
              {/* Achievements — Jack's call: surfaces proof-of-capability
                  the twin can drop into credibility-bound deal moments
                  (e.g. "Jackson raised $2m at $20m post and built X").
                  Renders on the public portfolio + the community member
                  summary card so other people can vouch quickly. */}
              <DeepField
                label="What is a list of your greatest life achievements?"
                helper="The wins your twin should reach for when establishing trust — companies built, rounds raised, milestones hit, recognition earned, hard things you finished. One per line is fine; the twin will pick the right one for each conversation."
                placeholder={`e.g.\nRaised $2m at $20m post for Persist Ventures\nLed BUMP to 30k MAUs in 6 weeks\nWon the 2024 ASI Hackathon`}
                rows={5}
                value={state.achievements}
                onChange={(v) => set("achievements", v)}
              />
            </div>

            {/* Save button — RENDERED ONLY on the Refine step, ONLY at the
                bottom, ONLY as a deliberate submit. Padded away from inputs
                with a divider so an accidental misclick can't reach it.
                Unique key forces a fresh DOM node so React reconciliation
                can never swap a "continue" button into this position. */}
            <div
              style={{
                marginTop: 32,
                paddingTop: 24,
                borderTop: "1px solid var(--border)",
                display: "flex",
                flexDirection: "column",
                alignItems: "flex-start",
                gap: 8
              }}
            >
              <div
                className="retro-label"
                style={{ color: "var(--amber-bright)" }}
              >
                ready to ship?
              </div>
              <p
                className="text-sm"
                style={{ color: "var(--text-dim)", maxWidth: 540 }}
              >
                Everything above gets saved as your twin&apos;s playbook.
                You can edit any of it later from this same page.
              </p>
              <button
                key="save-twin-final"
                type="submit"
                disabled={
                  !state.display_name.trim() ||
                  !phoneReady ||
                  !state.goals.trim() ||
                  !state.deal_preferences.trim()
                }
                className="retro-btn retro-btn-primary"
                style={{ padding: "10px 18px", marginTop: 6 }}
              >
                save twin & go to dashboard →
              </button>
            </div>
          </div>
        )}
      </div>
    </form>
  );
}

function Field({
  label,
  value,
  onChange
}: {
  label: string;
  value: string;
  onChange: (v: string) => void;
}) {
  return (
    <label className="block">
      <div className="text-sm font-semibold" style={{ color: "var(--text)" }}>
        {label}
      </div>
      <textarea
        value={value}
        onChange={(e) => onChange(e.target.value)}
        rows={2}
        className="retro-input mt-1"
      />
    </label>
  );
}

/**
 * Bottom-of-step Next button. Lives at the foot of every step OTHER than
 * Refine (Refine has its own deliberate Save button). Jack: "make sure
 * each step has a next button at the bottom of the page after someone
 * finishes the thing." The pill-row up top still works for power users;
 * this is the primary CTA for first-timers who scroll through the form.
 */
function StepFooterNext({
  canAdvance,
  hasContent,
  onNext
}: {
  canAdvance: boolean;
  hasContent: boolean;
  onNext: () => void;
}) {
  return (
    <div
      style={{
        marginTop: 28,
        paddingTop: 16,
        borderTop: "1px solid var(--border)",
        display: "flex",
        justifyContent: "flex-end",
        alignItems: "center",
        gap: 8
      }}
    >
      {!hasContent && (
        <span className="retro-dim text-xs">
          you can always come back to this
        </span>
      )}
      <button
        key="step-footer-next"
        type="button"
        onClick={onNext}
        disabled={!canAdvance}
        className={
          hasContent
            ? "retro-btn retro-btn-primary"
            : "retro-btn"
        }
        style={{ padding: "9px 18px", fontSize: 14 }}
      >
        {hasContent ? "next step →" : "skip →"}
      </button>
    </div>
  );
}

function DeepField({
  label,
  helper,
  placeholder,
  rows,
  value,
  onChange
}: {
  label: string;
  helper: string;
  placeholder: string;
  rows: number;
  value: string;
  onChange: (v: string) => void;
}) {
  return (
    <label className="block">
      <div
        className="text-base font-semibold"
        style={{ color: "var(--text)" }}
      >
        {label}
      </div>
      <div
        className="text-xs mt-1.5 leading-relaxed"
        style={{ color: "var(--text-dim)" }}
      >
        {helper}
      </div>
      <textarea
        value={value}
        onChange={(e) => onChange(e.target.value)}
        rows={rows}
        placeholder={placeholder}
        className="retro-input mt-2"
        style={{ minHeight: rows * 24 }}
      />
    </label>
  );
}
